backend:
  name: github
  repo: GeoGuess/Geoguess.games
  branch: master
media_folder: ".vuepress/public/"
public_folder: "/"
display_url: https://geoguess.games/
collections:
  - label: "Home"
    name: "home"
    files:
      - name: "Home EN"
        label: "Home EN"
        file: "docs/README.md"
        slug: "{{slug}}" 
        show_preview_links: true
        fields:
          - {label: "Title", name: "heroText", widget: "string"}
          - {label: "tagline", name: "tagline", widget: "string"}
          - {label: "actionText", name: "actionText", widget: "string"}
          - label: "Features"
            name: "features"
            widget: "list"
            summary: '{{fields.title}}'
            fields:
             - {label: "Title", name: "title", widget: "string"}
             - {label: "details", name: "details", widget: "string"}
          - label: "blocks"
            name: "blocks"
            widget: "list"
            summary: '{{fields.title}}'
            fields:
             - {label: "Title", name: "title", widget: "string"}
             - {label: "text", name: "text", widget: "string"}
             - {label: "altImg", name: "altImg", widget: "string"}
             - {label: "srcImg", name: "srcImg", widget: image}
          - {label: "footer", name: "footer", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "Home FR"
        label: "Home FR"
        file: "docs/fr/README.md"
        slug: "{{slug}}"
        show_preview_links: true
        fields:
          - {label: "Title", name: "heroText", widget: "string"}
          - {label: "tagline", name: "tagline", widget: "string"}
          - {label: "actionText", name: "actionText", widget: "string"}
          - label: "Features"
            name: "features"
            widget: "list"
            summary: '{{fields.title}}'
            fields:
             - {label: "Title", name: "title", widget: "string"}
             - {label: "details", name: "details", widget: "string"}
          - label: "blocks"
            name: "blocks"
            widget: "list"
            summary: '{{fields.title}}'
            fields:
             - {label: "Title", name: "title", widget: "string"}
             - {label: "text", name: "text", widget: "string"}
             - {label: "altImg", name: "altImg", widget: "string"}
             - {label: "srcImg", name: "srcImg", widget: image}
          - {label: "footer", name: "footer", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "Guide" # Used in routes, e.g., /admin/collections/blog
    label: "Guide" # Used in the UI
    folder: "docs/guide" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    show_preview_links: true
    summary: "{{filename}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Dev"
    label: "Dev"
    folder: "docs/guide/dev" 
    create: true 
    slug: "{{slug}}" 
    summary: "{{filename}}"
    show_preview_links: true
    fields:
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Guide FR" 
    label: "Doc" 
    folder: "docs/fr/guide"
    create: true 
    slug: "{{slug}}" 
    summary: "{{filename}}"
    show_preview_links: true
    fields: 
      - {label: "Body", name: "body", widget: "markdown"}
